# Generated by Django 4.0 on 2023-02-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchmate_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
