# Generated by Django 4.0 on 2023-02-10 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchmate_app', '0004_alter_streamplatform_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchmate_app.streamplatform'),
            preserve_default=False,
        ),
    ]
